WebGames/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGames.Libs;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using WebGames.Libs.Games;

namespace WebGames.Controllers
{
    [Authorize(Roles = "player")]
    public class DemoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MasterMind()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Mastermind);

            return GetPage(activeGameInfo);
        }

        public ActionResult Questions()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Questions);

            return GetPage(activeGameInfo);
        }

        public ActionResult Whackamole()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Whackamole);

            return GetPage(activeGameInfo);
        }

        public ActionResult Escape_1()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Escape_1);

            return GetPage(activeGameInfo);
        }

        public ActionResult Escape_2()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Escape_2);

            return GetPage(activeGameInfo);
        }

        public ActionResult Escape_3()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Escape_3);

            return GetPage(activeGameInfo);
        }

        public ActionResult Juggler()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Juggler);

            return GetPage(activeGameInfo);
        }

        public ActionResult Adespotabalakia()
        {
            ActiveUserGameInfo activeGameInfo = GetGameInfo(GameKeys.Adespotabalakia);

            return GetPage(activeGameInfo);
        }

        private ActiveUserGameInfo GetGameInfo(string GameKey)
        {
            var userId = User.Identity.GetUserId();
            var GameData = GameManager.GameDict[GameKey];

            var scoreData = GameData.SM.GetUserScore(userId);
            var activeGameInfo = new ActiveUserGameInfo()
            {
                ActiveGameDataModel = new ActiveGameData()
                {
                    ActiveGameKey = "",
                    Messages = new Dictionary<string, string>()
                },
                ActiveLevel = scoreData.Levels + 1,
                AvailableLevels = GameData.AvailableLevels,
                Folder = GameData.Folder,
                GameScore = scoreData.Score,
                IsDemo = false,
                LevelAsPage = GameData.LevelAsPage,
                Page = GameData.Page,
                RemainingTime = UserGameManager.GetUserRemainingTime(userId).RemainingTimeInSeconds
            };
            return activeGameInfo;
        }

        public ActionResult ActiveGameAfter()
        {
            var message = "Τέλος του Demo";
            return View("ActiveGameAfter", new Dictionary<string, string>() { { "message", message } });

        }

        private ActionResult GetPage(ActiveUserGameInfo gameInfo, string Page = "")
        {
            ActionResult ViewRes = null;
            // Active game was found
            if (gameInfo.ActiveGameDataModel != null)
            {
                // No remaining time
                if (gameInfo.RemainingTime <= 0)
                {
                    ViewRes = RedirectToAction("ActiveGameAfter", new { status = "outoftime" });
                } // no available levels
                else if (gameInfo.AvailableLevels > 0 && gameInfo.AvailableLevels < gameInfo.ActiveLevel)
                {
                    ViewRes = RedirectToAction("ActiveGameAfter", new { status = "success" });
                }
                else
                {
                    string ViewPageToDisplay = gameInfo.Folder;
                    if (Page != "")
                    {
                        ViewPageToDisplay += $"/{Page}";
                    }
                    else // it's the game so use the PageFolder for the file
                    {
                        ViewPageToDisplay += $"/{gameInfo.Page}";

                        // If level is on its own page
                        if (gameInfo.LevelAsPage)
                        {
                            // use level specific page
                            ViewPageToDisplay += $"-{gameInfo.ActiveLevel}";
                        }
                    }

                    ViewRes = View(ViewPageToDisplay, gameInfo);
                }
            }
            else
            {
                // Nothing was found
                ViewRes = View("NoActiveGame");
            }

            return ViewRes;
        }

    }
}

WebGames/Views/Demo/ActiveGameAfter.cshtml
<div>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="~/Content/Games/css/screens.css">

    <div class="wrapper">
        <div class="screen screen1">

            @(new HtmlString(Model["message"]))

        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
				jQuery.fn.center = function () {
		    this.css("position","absolute");
		    this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
		                                                $(window).scrollTop()) + "px");
		    this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
		                                                $(window).scrollLeft()) + "px");
		    return this;
		}
		$(window).on('resize', function(){
			$('.screen').center();
		});

		$(document).ready(function() {
			setTimeout(function(){ $('.screen').center(); }, 150);


});
    </script>
</div>

WebGames/Views/Demo/Index.cshtml
<div>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="~/Content/Games/css/screens.css">

    <div class="wrapper">
        <div class="screen screen1">


            @*<div class="list-group">
                    <a href="@Url.Action("Mastermind", "Demo")" class="list-group-item">Mastermind</a>
                    <a href="@Url.Action("Whackamole", "Demo")" class="list-group-item">Whackamole</a>
                    <a href="@Url.Action("Escape_1", "Demo")" class="list-group-item">Escape_1</a>
                    <a href="@Url.Action("Escape_2", "Demo")" class="list-group-item">Escape_2</a>
                    <a href="@Url.Action("Escape_3", "Demo")" class="list-group-item">Escape_3</a>
                    <a href="@Url.Action("Juggler", "Demo")" class="list-group-item">Juggler</a>
                    <a href="@Url.Action("Adespotabalakia", "Demo")" class="list-group-item">Adespotabalakia</a>
                    <a href="@Url.Action("Questions", "Demo")" class="list-group-item">Questions</a>
                </div>*@

            <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-4">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("Mastermind", "Demo")" role="button">ΜΑΝΤΕΨΕ ΤΙ ΜΑΝΤΕΨΑ</a>
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("Questions", "Demo")" role="button">ΚΛΕΙΔΙΑ</a>
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("Whackamole", "Demo")" role="button">WHACK A MOLE</a>
                </div>

                <div class="col-md-3 col-sm-3 col-xs-3">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("Escape_1", "Demo")" role="button">ΚΛΟΥΒΙΑ ΚΛΟΥΒΙΑ</a>
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("Juggler", "Demo")" role="button">ΑΤΕΛΕΙΩΤΟ ΣΚΟΙΝΑΚΙ</a>
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("Adespotabalakia", "Demo")" role="button">ΑΔΕΣΠΟΤΑ ΜΠΑΛΑΚΙΑ</a>
                </div>
            </div>

        </div>
    </div>
</div>